core/urls.py
from django.urls import path, include
from .views import *

app_name = 'core'

urlpatterns = [
    path('menu/', Menu.as_view(),name='menu'),
    path('inscricao/', UsuarioInscricao.as_view(),name='usuario_inscricao'),
    path('sucesso/', SucessoInscricao.as_view(),name='sucesso_inscricao'),
]

fornecedor/urls.py
from django.urls import path
from .views import *
# ou FornecedorCreate,FornecedorList,FornecedorUpdate,
# FornecedorDelete,FornecedorDetail

# Definir namespace como informado em urls projeto
app_name = 'fornecedor'

urlpatterns = [
    path('create/', FornecedorCreate.as_view(), name='fornecedor_create'),
    #path('read/', FornecedorList.as_view(), name='fornecedor_read'),
    path('read/', FornecedorListFiltro.as_view(), name='fornecedor_read'),
    path('update/<int:pk>', FornecedorUpdate.as_view(), name='fornecedor_update'),
    path('delete/<int:pk>', FornecedorDelete.as_view(), name='fornecedor_delete'),
    path('detail/<int:pk>', FornecedorDetail.as_view(), name='fornecedor_detail'),
]

produto/urls.py
from django.urls import path
from .views import *
# ou ProdutoCreate,ProdutoList,ProdutoUpdate,
# ProdutoDelete,ProdutoDetail

# Definir namespace como informado em urls projeto
app_name = 'produto'

urlpatterns = [
    path('create/', ProdutoCreate.as_view(), name='produto_create'),
    #path('read/', ProdutoList.as_view(), name='produto_read'),
    path('read/', ProdutoListFiltro.as_view(), name='produto_read'),
    path('update/<int:pk>', ProdutoUpdate.as_view(), name='produto_update'),
    path('delete/<int:pk>', ProdutoDelete.as_view(), name='produto_delete'),
    path('detail/<int:pk>', ProdutoDetail.as_view(), name='produto_detail'),
]

sisgg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from core.views import Entrar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Entrar.as_view(),name='entrar'),
    #path('',  TemplateView.as_view(template_name='core/index.html')),
    path('core/',include('core.urls',namespace='core')),
    path('fornecedor/',include('fornecedor.urls',namespace='fornecedor')),
    path('produto/',include('produto.urls',namespace='produto')),
]

core/models.py
from django.db import models

# Create your models here.
class Usuario(models.Model):
    SEXO_CHOICES = [
        ["F", "Feminino"],
        ["M", "Masculino"],
        ["N", "Nenhuma das opções"]
    ]
    nome = models.CharField(max_length=40,verbose_name='Nome')
    email = models.EmailField(max_length=140,verbose_name = 'E-mail',unique=True)
    senha = models.CharField(max_length=8,verbose_name = 'Senha')
    sexo = models.CharField(max_length=1, choices=SEXO_CHOICES,verbose_name='Sexo')
    
    def __str__(self):
        return self.nome

core/forms.py
from django import forms
from core.models import Usuario

class UsuarioFormInscricao(forms.Form):
    #<option value="" selected="selected" hidden="hidden">Choose here</option>
    SEXO_CHOICES = [
        ["","Selecione o sexo"],
        ["F", "Feminino"],
        ["M", "Masculino"],
        ["N", "Nenhuma das opções"]
    ]
    nome = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Digite seu nome'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Digite seu email'}))
    sexo = forms.ChoiceField(initial='',choices=SEXO_CHOICES,widget=forms.Select(attrs={'class':'form-control'}))
    senha = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Digite sua senha','maxlength':'8'}))
    confirma_senha = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Repita sua senha','maxlength':'8'}))

class UsuarioFormInscricao_OR(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['nome','email','senha','sexo']

class UsuarioFormEntrar(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Digite seu email'}))
    senha = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Digite sua senha','maxlength':'8'}))

    



        
        


    

core/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView,TemplateView
from django.views.generic.edit import FormView
from .models import Usuario
from .forms import UsuarioFormInscricao, UsuarioFormEntrar
from django.db.models import Q

# Create your views here.
class UsuarioCreate_OR_OLD(CreateView):
    model = Usuario
    form = UsuarioFormInscricao()
    fields = ['nome','email','senha','sexo']
    success_url = reverse_lazy('core:sucesso_inscricao')

class UsuarioInscricao(FormView):
    form_class = UsuarioFormInscricao
    model = Usuario
    success_url = reverse_lazy('core:sucesso_inscricao')
    template_name = "core/usuario_form.html"

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        #form.send_email()
        #dados_form = form.data
        #if (dados_form['senha'] != dados_form['confirma_senha']):  ou
        if (self.request.POST.get('senha') != self.request.POST.get('confirma_senha')):
           self.mensagem = 'Senha e confirmação de senha não coincidem!'
           return super().form_invalid(form)
        elif Usuario.objects.filter(email=self.request.POST.get('email')):
           self.mensagem = 'Já existe um usuário inscrito com este e-mail!'
           return super().form_invalid(form)
        else:
            usu_nome = self.request.POST.get('nome')
            usu_email = self.request.POST.get('email')
            usu_senha = self.request.POST.get('senha')
            usu_sexo = self.request.POST.get('sexo')
            novo_usuario = Usuario(nome=usu_nome,email=usu_email,senha=usu_senha,sexo=usu_sexo)
            novo_usuario.save()
            return super().form_valid(form)
        #   new_post = Post(title=post_title, slug=post_slug, body=post_body, author=post_author, status=post_status)
        #   new_post.save()
        #   return redirect('blog:post_list')
        #FBV
        #if not form.is_valid():
        #   return render(request, 'ticket_novo.html',{'form': form})
    def get_context_data(self, **kwargs):
        context = super(UsuarioInscricao, self).get_context_data(**kwargs)
        context['form'] = UsuarioFormInscricao # Insere o form no contexto do template
        #print('TESTE',self.request.POST.get('email'))
        if not self.request.POST.get('email'):
            self.mensagem = ''
        context['mensagem'] = self.mensagem
        return context

class Entrar(FormView):
    form_class = UsuarioFormEntrar
    success_url = reverse_lazy('core:menu') #temporario
    template_name = "core/index.html"
    model = Usuario

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        #form.send_email()
        filtro1 = self.request.POST.get('email')
        filtro2 = self.request.POST.get('senha')
        #print('FILTRO1 ',filtro1)
        #print('FILTRO2 ',filtro2)
        #print('passei')
        criterion1 = Q(email=filtro1)
        criterion2 = Q(senha=filtro2)
        if Usuario.objects.filter(email=self.request.POST.get('email'), senha=self.request.POST.get('senha')):
            return super().form_valid(form)
        else:
            return super().form_invalid(form)
        #return super().form_valid(form)
        
    def get_context_data(self, **kwargs):
        context = super(Entrar, self).get_context_data(**kwargs)
        context['form'] = UsuarioFormEntrar # Insere o form no contexto do template
        #print('TESTE',self.request.POST.get('email'))
        if self.request.POST.get('email'):
            context['mensagem'] = 'E-mail e/ou senha inválidos!'
        else:
            context['mensagem'] = ''
        return context


class SucessoInscricao(TemplateView):
    template_name = "core/sucesso_inscricao.html"

class Menu(TemplateView):
    template_name = "core/menu.html"

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>G&G Cotações</title>
   <!--Made with love by Mutiullah Samim -->

	<!--Bootsrap 4 CDN-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<!--Custom styles-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}">
</head>
<body>
<div class="container">
	{% block conteudo %}
	{% endblock %}
</div>
</body>
</html>

core/templates/core/base_menu.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>G&G Cotações</title>
   <!--Made with love by Mutiullah Samim -->

	<!--Bootsrap 4 CDN-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<!--Custom styles-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/estilo_menu.css' %}">
</head>
<body>
    {% load static %}
    <input type="checkbox" id="chec">
    <label for="chec" class="menu">
        <img src="{% static '/images/menu.png' %}" alt="Menu">
    </label>
    <nav>
    <ul class="menu menu2">
        <li><a href="{% url 'core:menu' %}" class="menu menu2">HOME</a></li>
        <li><a href="{% url 'fornecedor:fornecedor_read' %}" class="menu menu2">FORNECEDOR</a></li>
        <li><a href="{% url 'produto:produto_read' %}" class="menu menu2">PRODUTO</a></li>
        <li><a href="/" class="menu menu2">SAIR</a></li>
    </ul>
    </nav>
    <div class="container">
        {% block conteudo %}
        {% endblock %}
    </div>
</body>
</html>

core/templates/core/index-original.html
{% extends 'core/base.html' %}
{% block conteudo %}
<div class="d-flex justify-content-center h-100">
    <div class="card">
        <div class="card-header">
            <h3>G & G COTAÇÕES</h3>
            <div class="d-flex justify-content-end social_icon">
                <span><i class="fab fa-facebook-square"></i></span>
            </div>
        </div>
        <div class="card-body">
            <form>
                <div class="input-group form-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-user"></i></span>
                    </div>
                    <input type="text" class="form-control" placeholder="Usuário">
                </div>
                <div class="input-group form-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-key"></i></span>
                    </div>
                    <input type="password" class="form-control" placeholder="Senha">
                </div>
                <div class="row align-items-center remember">
                    <p></p>
                </div>
                <div class="form-group">
                    <input type="submit" value="Login" class="btn float-right login_btn">
                </div>
            </form>
        </div>
        <div class="card-footer">
            <div class="d-flex justify-content-center links">
                Não possui uma conta?<a href="{% url 'core:usuario_create' %}">Inscrever-se</a>
            </div>
            <div class="d-flex justify-content-center">
                <a href="#">Esqueceu sua senha??</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% block conteudo %}
<div class="d-flex justify-content-center h-100">
    <div class="card">
        <div class="card-header">
            <h3>G & G COTAÇÕES</h3>
            <div class="d-flex justify-content-end social_icon">
                <span><i class="fab fa-facebook-square"></i></span>
            </div>
        </div>
        <div class="card-body">
            <form method="POST"> 
                {% csrf_token %}
                E-mail
                <div class="input-group form-group">
                    <div class="input-group-prepend"> 
                        <span class="input-group-text"><i class="fas fa-user"></i>@</span>
                    </div>
                     <!--<input type="text" class="form-control" placeholder="Usuário"> -->
                    {{ form.email }}
                </div>
                Senha
                <div class="input-group form-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-key"></i></span>
                    </div>
                    <!--<input type="password" class="form-control" placeholder="Senha">-->
                    {{ form.senha }}
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-warning float-right">
                            <i class="fas fa-sign-in-alt"></i> Entrar</button>
                </div>
                {% if mensagem %}
                <div class="form-group">
                    {{ mensagem }}
                </div>{% endif %}
            </form>
        </div>
        <div class="card-footer">
            <div class="d-flex justify-content-center links">
                Não possui uma conta?<a href="{% url 'core:usuario_inscricao' %}" style="color:#FFC312">Inscreva-se</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

core/templates/core/index_v2_pos_original.html
{% extends 'core/base.html' %}
{% block conteudo %}
<div class="d-flex justify-content-center h-100">
    <div class="card">
        <div class="card-header">
            <h3>G & G COTAÇÕES</h3>
            <div class="d-flex justify-content-end social_icon">
                <span><i class="fab fa-facebook-square"></i></span>
            </div>
        </div>
        <div class="card-body">
            <form>
                <div class="input-group form-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-user"></i></span>
                    </div>
                    <input type="text" class="form-control" placeholder="Usuário">
                </div>
                <div class="input-group form-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-key"></i></span>
                    </div>
                    <input type="password" class="form-control" placeholder="Senha">
                </div>
                <div class="row align-items-center remember">
                    <p></p>
                </div>
                <div class="form-group">
                    <input type="submit" value="Login" class="btn float-right login_btn">
                </div>
            </form>
        </div>
        <div class="card-footer">
            <div class="d-flex justify-content-center links">
                Não possui uma conta?<a href="{% url 'core:usuario_create' %}">Inscrever-se</a>
            </div>

        </div>
    </div>
</div>
{% endblock %}

core/templates/core/menu.html
{% extends 'core/base_menu.html' %}
{% block conteudo %}
<!-- CONTEÚDO -->
<div class="d-flex justify-content-center h-100">
        <div class="card">
            <div class="card-header">
                <h3>G & G COTAÇÕES</h3>
            </div>
            <div class="card-body">
                <h5>Seja bem-vindo!</h5>
            </div>
        </div>
    </div>
{% endblock %}

core/templates/core/sucesso_inscricao.html
{% extends 'core/base.html' %}
{% block conteudo %}
<div class="d-flex justify-content-center h-100">
    <div class="card">
        <div class="card-header">
            <h3>G & G COTAÇÕES</h3>
        </div>
        <div class="card-body">
            <h5>Inscrição efetuada com sucesso!</h5>
            <div>
                <p></p>
                <a href="/" class="btn btn-warning float-right"><i class="fas fa-sign-in-alt"></i> Entrar</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

core/templates/core/usuario_form-original.html
{% extends 'core/base.html' %}
{% block conteudo %}
<div class="d-flex justify-content-center mb-5"></div>
    <div class="card-increver-se">
        <div class="card-header">
            <h3>G & G COTAÇÕES</h3>
            <h3>Inscrever-se</h3>
        </div>
        <div class="card-body">
            <form id="formExemplo" data-toggle="validator" role="form" method="post">
                <div class="form-group">
                    <label for="textNome" class="control-label">Nome</label>
                    <input id="textNome" class="form-control" placeholder="Digite seu Nome..." type="text">
                </div>
                <div class="form-group">
                    <label for="inputEmail" class="control-label">Email</label>
                    <input id="inputEmail" class="form-control" placeholder="Digite seu E-mail" type="email">
                </div>
            
                <div class="form-group">
                    <label for="inputPassword" class="control-label">Senha</label>
                    <input type="password" class="form-control" id="inputPassword" placeholder="Digite sua Senha...">
                </div>
                <div class="form-group">
                    <label for="inputConfirm" class="control-label">Confirmação a Senha</label>
                    <input type="password" class="form-control" id="inputConfirm" placeholder="Confirme sua Senha...">
                </div>
                <div class="form-group">
                    <button class="boton btn-lg btn-warning btn-block" type="submit">Registrar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

core/templates/core/usuario_form.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% block conteudo %}
<div class="d-flex justify-content-center"></div>
    <div class="card-increver-se">
        <div class="card-header">
            <h3>G & G COTAÇÕES</h3>
            <h4>Inscrição</h4>
        </div>
        <div class="card-body">
            <form id="formExemplo" data-toggle="validator" role="form" method="post">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.nome|as_crispy_field }}
                </div>
                <div class="form-group">
                    {{ form.email|as_crispy_field }}
                </div>
                <div class="form-group">
                        {{ form.sexo|as_crispy_field }}
                    </div>           
                <div class="form-group">
                    {{ form.senha|as_crispy_field }}
                </div>
                <div class="form-group">
                        {{ form.confirma_senha|as_crispy_field }}
                </div>
                <!--<div class="form-group">
                    <label for="inputConfirm" class="control-label">Confirmação de Senha</label>
                    <input type="password" name="confirma_senha" class="form-control" id="inputConfirm" placeholder="Confirme sua Senha...">
                </div>-->
                <div class="form-group">
                    <button class="btn btn-warning" type="submit"><i class="far fa-save"></i> Registrar</button>
                    <a href="javascript:void(0)" onClick="history.go(-1); return false;" class="btn btn-warning">
                            <i class="far fa-caret-square-left"></i> Voltar</a>
                </div>
                {% if mensagem %}
                <div class="form-group">
                        {{ mensagem }}
                </div>{% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}