core/urls.py
from django.urls import path, include
from .views import *

app_name = 'core'

urlpatterns = [
    path('menu/', Menu.as_view(),name='menu'),
    path('inscricao/', UsuarioInscricao.as_view(),name='usuario_inscricao'),
    path('sucesso/', SucessoInscricao.as_view(),name='sucesso_inscricao'),
]

fornecedor/urls.py
from django.urls import path
from .views import *
# ou FornecedorCreate,FornecedorList,FornecedorUpdate,
# FornecedorDelete,FornecedorDetail

# Definir namespace como informado em urls projeto
app_name = 'fornecedor'

urlpatterns = [
    path('create/', FornecedorCreate.as_view(), name='fornecedor_create'),
    #path('read/', FornecedorList.as_view(), name='fornecedor_read'),
    path('read/', FornecedorListFiltro.as_view(), name='fornecedor_read'),
    path('update/<int:pk>', FornecedorUpdate.as_view(), name='fornecedor_update'),
    path('delete/<int:pk>', FornecedorDelete.as_view(), name='fornecedor_delete'),
    path('detail/<int:pk>', FornecedorDetail.as_view(), name='fornecedor_detail'),
]

sisgg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from core.views import Entrar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Entrar.as_view(),name='entrar'),
    #path('',  TemplateView.as_view(template_name='core/index.html')),
    path('core/',include('core.urls',namespace='core')),
    path('fornecedor/',include('fornecedor.urls',namespace='fornecedor')),
    path('produto/',include('produto.urls',namespace='produto')),
]

fornecedor/models.py
from django.db import models

# Create your models here.
class Fornecedor(models.Model):
    nome = models.CharField(max_length=50, null=False,
                            verbose_name="Nome/Razão Social")
    cnpj = models.CharField(max_length=19, null=False, verbose_name="CNPJ",
                            unique=True, help_text="(Formato 99.999.999/9999-99)")
    ddd_telefone = models.CharField(
        max_length=2, verbose_name="DDD", help_text="(Formato 99)")
    telefone = models.CharField(
        max_length=10, verbose_name="Telefone", help_text="(Formato 99999-9999)")

    def __str__(self):
        return self.nome

fornecedor/forms.py
# Arquivo criado para implementar filtro na view listview
from django import forms
#from fornecedor.models import Fornecedor

class FornecedorMeuFormFiltro(forms.Form):
    nome = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Digite o nome'}))
    #class Meta:
    #    model = Fornecedor
    #    fields = ['nome']

fornecedor/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.views.generic.edit import FormView
from .models import Fornecedor
from .forms import FornecedorMeuFormFiltro
# Create your views here.

class FornecedorList(ListView):
    model = Fornecedor
    

class FornecedorListFiltro(ListView): # Optamos por criar uma nova View
    #model = Fornecedor
    #template_name = 'fornecedor/fornecedor_list.html'
    form_class = FornecedorMeuFormFiltro
    model = Fornecedor
    #success_url = reverse_lazy('core:sucesso_inscricao')
    template_name = "fornecedor/fornecedor_list.html"

    def get_queryset(self, **kwargs):
        filtro1 = self.request.GET.get('nome', '') # Pega o conteúdo do campo nome do form
        #print("FILTRO1",filtro1)
        modo_busca = self.request.GET.get('modo_busca', '1')
        #print("MODO BUSCA ANTES")
        #print("MODO BUSCA",modo_busca)
        #print("MODO BUSCA DEPOIS")
        if not filtro1:  # Retorna queryset vazio se for primeira vez
            return Fornecedor.objects.none() 
        elif filtro1.strip() == '*':  # Traz todos se campo nome = '*'
            return Fornecedor.objects.all()
        elif modo_busca == '1':
            return Fornecedor.objects.filter(nome__startswith=filtro1)
        elif modo_busca == '2':
            return Fornecedor.objects.filter(nome__icontains=filtro1)
        elif modo_busca == '3':
            return Fornecedor.objects.filter(nome__endswith=filtro1)
        # Filtra dessa forma caso não ocorra nenhuma condição acima
        return Fornecedor.objects.filter(nome__startswith=filtro1)

    def get_context_data(self, **kwargs):
        context = super(FornecedorListFiltro, self).get_context_data(**kwargs)
        context['form'] = FornecedorMeuFormFiltro # Insere o form no contexto do template
        # Pegar o valor da variável de pesquisa. Se for vazio (=Falso) é porque é a primeira 
        # vez mas para o contexto do template será igual a 1 (=Verdadeiro)
        primeira_vez = self.request.GET.get('nome', '')
        if primeira_vez:
            context['primeira_vez'] = 0
        else:
            context['primeira_vez'] = 1
        #print("PRIMEIRA VEZ",primeira_vez)
        return context


class FornecedorCreate(CreateView):
    model = Fornecedor
    fields = ['nome', 'cnpj', 'ddd_telefone', 'telefone']
    success_url = reverse_lazy('fornecedor:fornecedor_read')


class FornecedorUpdate(UpdateView):
    model = Fornecedor
    fields = ['nome', 'cnpj', 'ddd_telefone', 'telefone']
    success_url = reverse_lazy('fornecedor:fornecedor_read')


class FornecedorDelete(DeleteView):
    model = Fornecedor
    success_url = reverse_lazy('fornecedor:fornecedor_read')


class FornecedorDetail(DetailView):
    model = Fornecedor
    fields = ['nome', 'cnpj', 'ddd_telefone', 'telefone']

fornecedor/templates/fornecedor/base_menu_NÃO_USAR.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>G&G Cotações</title>
   <!--Made with love by Mutiullah Samim -->

	<!--Bootsrap 4 CDN-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<!--Custom styles-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/estilo_menu.css' %}">
</head>
<body>
    {% load static %}
    <input type="checkbox" id="chec">
    <label for="chec">
        <img src="{% static '/images/menu.png' %}" alt="Menu">
    </label>
    <nav>
    <ul>
        <li><a href="">HOME</a></li>
        <li><a href="">FORNECEDOR</a></li>
        <li><a href="">PRODUTO</a></li>
        <li><a href="/">SAIR</a></li>
        </ul>
    </nav>
    <div class="container">
        {% block conteudo %}
        {% endblock %}
    </div>
</body>
</html>

fornecedor/templates/fornecedor/fornecedor_confirm_delete.html
{% extends 'core/base_menu.html' %}
{% block conteudo %}
<div class="d-flex justify-content-center mb-5"></div>
    <div class="card-fornecedor-excluir">
        <div class="card-header">
            <h3>G & G COTAÇÕES</h3>
            <h4>Fornecedor</h4>
        </div>
        <div class="card-body">
            <h4>Deseja realmente apagar este registro?</h4>
            <br>
            <p><strong>Código:</strong> {{ fornecedor.id | stringformat:'04d' }}</p>
            <p><strong>Nome/Razão Social:</strong> {{ fornecedor.nome }}</p>
            <p><strong>CNPJ:</strong> {{ fornecedor.cnpj }}</p>
            <p><strong>Telefone:</strong> ({{fornecedor.ddd_telefone}}) {{fornecedor.telefone}}</p>
            <form id="formExemplo" data-toggle="validator" role="form" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">
                    <i class="far fa-trash-alt"></i> Excluir</button>
                <a href="javascript:void(0)" onClick="history.go(-1); return false;" 
                    class="btn btn-success"><i class="far fa-window-close"></i> Cancelar</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

fornecedor/templates/fornecedor/fornecedor_detail.html
{% extends 'core/base_menu.html' %}
{% block conteudo %}
<div class="d-flex justify-content-center mb-5"></div>
    <div class="card-fornecedor-detalhe">
        <div class="card-header">
            <h3>G & G COTAÇÕES</h3>
            <h4>Fornecedor</h4>
        </div>
        <div class="card-body">
            <p><strong>Código:</strong> {{ fornecedor.id | stringformat:'04d' }}</p>
            <p><strong>Nome/Razão Social:</strong> {{ fornecedor.nome }}</p>
            <p><strong>CNPJ</strong>: {{ fornecedor.cnpj }}</p>
            <p><strong>Telefone:</strong> ({{fornecedor.ddd_telefone}}) {{fornecedor.telefone}}</p>
            <a href="{% url 'fornecedor:fornecedor_delete' fornecedor.id %}" class="btn btn-danger"><i
                    class="far fa-trash-alt"></i> Excluir</a>
            <a href="{% url 'fornecedor:fornecedor_update' fornecedor.id %}" class="btn btn-warning">
                <i class="far fa-edit"></i> Alterar</a>
            <a href="javascript:void(0)" onClick="history.go(-1); return false;" class="btn btn-success">
            <i class="far fa-caret-square-left"></i> Voltar</a>
            <!-- <a href="{% url 'fornecedor:fornecedor_read' %}" class="btn btn-success">
                <i class="fas fa-search"></i>Consultar</a> -->
        </div>
    </div>
</div>
{% endblock %}

fornecedor/templates/fornecedor/fornecedor_form.html
{% extends 'core/base_menu.html' %}
{% load crispy_forms_tags %}
{% block conteudo %}
<div class="d-flex justify-content-center mb-5"></div>
    <div class="card-fornecedor-alterar">
        <div class="card-header">
            <h3>G & G COTAÇÕES</h3>
            <h4>Fornecedor</h4>
        </div>
        <div class="card-body">
            <form id="formExemplo" data-toggle="validator" role="form" method="post">
                <table class="table-sm table-responsive-sm">
                    {% csrf_token %}
                    {{ form|crispy }}
                </table>
                <button type="submit" class="btn btn-warning">
                    <i class="far fa-save"></i> Salvar</button>
                <a href="javascript:void(0)" onClick="history.go(-1); return false;" 
                    class="btn btn-success"><i class="far fa-window-close"></i> Cancelar</a>       
            </form>
  </div>
</div>
{% endblock %}

fornecedor/templates/fornecedor/fornecedor_list.html
{% extends 'core/base_menu.html' %}
{% load crispy_forms_tags %}
{% block conteudo %}
<div class="d-flex justify-content-center mb-5"></div>
    <div class="card-fornecedor">
        <div class="card-header">
            <h3>G & G COTAÇÕES</h3>
            <h4>Fornecedor</h4>
        </div>
        <div class="card-body">
            <form id="formExemplo" data-toggle="validator" role="form" action="." method="get">
              {% csrf_token %}
              <div class="form-group">
                  {{ form.nome|as_crispy_field }}
              </div>
              <div class="form-group">
                  <input type="radio" name="modo_busca" id="inicia" value="1" checked="checked">
                  <label for="inicia" class="control-label">Inicia com &nbsp;&nbsp;</label>
                  <input type="radio" name="modo_busca" id="contem" value="2">
                  <label for="contem" class="control-label">Contém &nbsp;&nbsp; </label>
                  <input type="radio" name="modo_busca" id="termina" value="3">
                  <label for="termina" class="control-label">Termina com</label>
              </div>    
              <div class="form-group">
                  <a href="{% url 'fornecedor:fornecedor_create' %}" class="btn btn-warning"><i class="far fa-file"></i> Novo</a>
                  <button type="submit" class="btn btn-warning"><i class="fas fa-search"></i> Pesquisar</button>
              </div>
              <div class="card-footer form-group">
                  {% if primeira_vez %}
                    <p>Cadastre um novo fornecedor ou faça uma nova consulta! (Nenhum item pesquisado)</p>
                  {% else %}
                    <p>
                        Total de registros: {{ object_list|length }} registro{{ object_list|pluralize }}
                        retornado{{ object_list|pluralize }} na pesquisa.
                    </p>
                  {% endif %}
              </div>         
            </form>
        </div>
    </div>
    <div style="color:#FFC312">
        {% if object_list %}
        <table class="table table-hover table-bordered table-sm table-responsive-sm">
          <thead class="text-center">
            <tr>
              <th colspan="4">Fornecedor{{ object_list|pluralize:'es' }}</th>
            </tr>
            <tr>
              <th>Nome/Razão Social</th>
              <th>CNPJ</th>
              <th>Telefone</th>
              <th>Ação</th>
            </tr>
          </thead>
          <tbody>
            {% for fornecedor in object_list %}
            <tr>
              <td>{{ fornecedor.nome }}</td>
              <td>{{ fornecedor.cnpj }}</td>
              <td>({{ fornecedor.ddd_telefone }}){{ fornecedor.telefone }}</td>
              <td>
                <a href="{% url 'fornecedor:fornecedor_delete' fornecedor.id %}" class="btn btn-danger"><i
                    class="far fa-trash-alt"></i> Excluir</a>
                <a href="{% url 'fornecedor:fornecedor_update' fornecedor.id %}" class="btn btn-warning"><i
                    class="far fa-edit"></i> Alterar</a>
                <a href="{% url 'fornecedor:fornecedor_detail' fornecedor.id %}" class="btn btn-success"><i
                    class="fas fa-search-plus"></i>Visualizar</a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}