core/urls.py
from django.urls import path, include
from .views import *

app_name = 'core'

urlpatterns = [
    path('menu/', Menu.as_view(),name='menu'),
    path('inscricao/', UsuarioInscricao.as_view(),name='usuario_inscricao'),
    path('sucesso/', SucessoInscricao.as_view(),name='sucesso_inscricao'),
]

produto/urls.py
from django.urls import path
from .views import *
# ou ProdutoCreate,ProdutoList,ProdutoUpdate,
# ProdutoDelete,ProdutoDetail

# Definir namespace como informado em urls projeto
app_name = 'produto'

urlpatterns = [
    path('create/', ProdutoCreate.as_view(), name='produto_create'),
    #path('read/', ProdutoList.as_view(), name='produto_read'),
    path('read/', ProdutoListFiltro.as_view(), name='produto_read'),
    path('update/<int:pk>', ProdutoUpdate.as_view(), name='produto_update'),
    path('delete/<int:pk>', ProdutoDelete.as_view(), name='produto_delete'),
    path('detail/<int:pk>', ProdutoDetail.as_view(), name='produto_detail'),
]

sisgg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from core.views import Entrar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Entrar.as_view(),name='entrar'),
    #path('',  TemplateView.as_view(template_name='core/index.html')),
    path('core/',include('core.urls',namespace='core')),
    path('fornecedor/',include('fornecedor.urls',namespace='fornecedor')),
    path('produto/',include('produto.urls',namespace='produto')),
]

produto/models.py
from django.db import models

# Create your models here.
class Produto(models.Model):
    nome = models.CharField(max_length=50,verbose_name='Produto')
    descricao = models.TextField(max_length=255,verbose_name='Descrição')
    preco = models.DecimalField(max_digits=9,decimal_places=2,verbose_name='Preço')
    fornecedor = models.ForeignKey('fornecedor.Fornecedor',on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

produto/forms.py
# Arquivo criado para implementar filtro na view listview
from django import forms
from produto.models import Produto
from fornecedor.models import Fornecedor

class ProdutoMeuFormFiltro(forms.Form):
    nome = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Digite o nome'}))
    #class Meta:
    #    model = Produto
    #    fields = ['nome']

#o form abaixo deu certo para create e update
#dimensionamento de linhas do Textarea (area minúsculo)
class ProdutoFormCreateUpdate(forms.ModelForm):
    nome = forms.CharField()
    descricao = forms.CharField(widget=forms.Textarea(attrs={'rows':'3','columns':'10'}))
    preco = forms.CharField()
    fornecedor = forms.ModelChoiceField(queryset=Fornecedor.objects.all())
    class Meta:
        model = Produto
        exclude = ['id']

produto/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.views.generic.edit import FormView
from .models import Produto
from .forms import ProdutoMeuFormFiltro, ProdutoFormCreateUpdate
# Create your views here.

class ProdutoList(ListView):
    model = Produto
    

class ProdutoListFiltro(ListView): # Optamos por criar uma nova View
    #model = Fornecedor
    #template_name = 'fornecedor/fornecedor_list.html'
    form_class = ProdutoMeuFormFiltro
    model = Produto
    #success_url = reverse_lazy('core:sucesso_inscricao')
    template_name = "produto/produto_list.html"

    def get_queryset(self, **kwargs):
        filtro1 = self.request.GET.get('nome', '') # Pega o conteúdo do campo nome do form
        #print("FILTRO1",filtro1)
        modo_busca = self.request.GET.get('modo_busca', '1')
        #print("MODO BUSCA ANTES")
        #print("MODO BUSCA",modo_busca)
        #print("MODO BUSCA DEPOIS")
        if not filtro1:  # Retorna queryset vazio se for primeira vez
            return Produto.objects.none() 
        elif filtro1.strip() == '*':  # Traz todos se campo nome = '*'
            return Produto.objects.all()
        elif modo_busca == '1':
            return Produto.objects.filter(nome__startswith=filtro1)
        elif modo_busca == '2':
            return Produto.objects.filter(nome__icontains=filtro1)
        elif modo_busca == '3':
            return Produto.objects.filter(nome__endswith=filtro1)
        # Filtra dessa forma caso não ocorra nenhuma condição acima
        return Produto.objects.filter(nome__startswith=filtro1)

    def get_context_data(self, **kwargs):
        context = super(ProdutoListFiltro, self).get_context_data(**kwargs)
        context['form'] = ProdutoMeuFormFiltro # Insere o form no contexto do template
        # Pegar o valor da variável de pesquisa. Se for vazio (=Falso) é porque é a primeira 
        # vez mas para o contexto do template será igual a 1 (=Verdadeiro)
        primeira_vez = self.request.GET.get('nome', '')
        if primeira_vez:
            context['primeira_vez'] = 0
        else:
            context['primeira_vez'] = 1
        #print("PRIMEIRA VEZ",primeira_vez)
        return context


class ProdutoCreate(CreateView):
    model = Produto
    form_class = ProdutoFormCreateUpdate
    #fields = ['nome', 'descricao', 'preco', 'fornecedor']
    success_url = reverse_lazy('produto:produto_read')


class ProdutoUpdate(UpdateView):
    model = Produto
    form_class = ProdutoFormCreateUpdate
    #fields = ['nome', 'descricao', 'preco', 'fornecedor']
    success_url = reverse_lazy('produto:produto_read')


class ProdutoDelete(DeleteView):
    model = Produto
    success_url = reverse_lazy('produto:produto_read')


class ProdutoDetail(DetailView):
    model = Produto
    fields = ['nome', 'descricao', 'preco', 'fornecedor']

produto/templates/produto/produto_confirm_delete.html
{% extends 'core/base_menu.html' %}
{% block conteudo %}
<div class="d-flex justify-content-center mb-5"></div>
    <div class="card-produto-excluir">
        <div class="card-header">
            <h3>G & G COTAÇÕES</h3>
            <h4>Produto</h4>
        </div>
        <div class="card-body">
            <h4>Deseja realmente apagar este registro?</h4>
            <br>
            <p><strong>Código:</strong> {{ produto.id | stringformat:'04d' }}</p>
            <p><strong>Nome:</strong> {{ produto.nome }}</p>
            <p><strong>Descrição:</strong> {{ produto.descricao }}</p>
            <p><strong>Preço:</strong> {{produto.preco}}</p>
            <p><strong>Fornecedor:</strong> {{produto.fornecedor}}</p>
            <form id="formExemplo" data-toggle="validator" role="form" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">
                    <i class="far fa-trash-alt"></i> Excluir</button>
                <a href="javascript:void(0)" onClick="history.go(-1); return false;" 
                    class="btn btn-success"><i class="far fa-window-close"></i> Cancelar</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

produto/templates/produto/produto_detail.html
{% extends 'core/base_menu.html' %}
{% block conteudo %}
<div class="d-flex justify-content-center mb-5"></div>
    <div class="card-produto-detalhe">
        <div class="card-header">
            <h3>G & G COTAÇÕES</h3>
            <h4>Produto</h4>
        </div>
        <div class="card-body">
            <p><strong>Código:</strong> {{ produto.id | stringformat:'04d' }}</p>
            <p><strong>Nome:</strong> {{ produto.nome }}</p>
            <p><strong>Descrição:</strong> {{ produto.descricao }}</p>
            <p><strong>Preço:</strong> {{produto.preco}}</p>
            <p><strong>Fornecedor:</strong> {{produto.fornecedor}}</p>
            <a href="{% url 'produto:produto_delete' produto.id %}" class="btn btn-danger"><i
                    class="far fa-trash-alt"></i> Excluir</a>
            <a href="{% url 'produto:produto_update' produto.id %}" class="btn btn-warning">
                <i class="far fa-edit"></i> Alterar</a>
            <a href="javascript:void(0)" onClick="history.go(-1); return false;" class="btn btn-success">
            <i class="far fa-caret-square-left"></i> Voltar</a>
            <!-- <a href="{% url 'produto:produto_read' %}" class="btn btn-success">
                <i class="fas fa-search"></i>Consultar</a> -->
        </div>
    </div>
</div>
{% endblock %}

produto/templates/produto/produto_form.html
{% extends 'core/base_menu.html' %}
{% load crispy_forms_tags %}
{% block conteudo %}
<div class="d-flex justify-content-center mb-5"></div>
    <div class="card-produto-alterar">
        <div class="card-header">
            <h3>G & G COTAÇÕES</h3>
            <h4>Produto</h4>
        </div>
        <div class="card-body">
            <form id="formExemplo" data-toggle="validator" role="form" method="post">
                <table class="table-sm table-responsive-sm">
                    {% csrf_token %}
                    {{ form|crispy }}
                </table>
                <button type="submit" class="btn btn-warning">
                    <i class="far fa-save"></i> Salvar</button>
                <a href="javascript:void(0)" onClick="history.go(-1); return false;" 
                    class="btn btn-success"><i class="far fa-window-close"></i> Cancelar</a>       
            </form>
  </div>
</div>
{% endblock %}

produto/templates/produto/produto_list.html
{% extends 'core/base_menu.html' %}
{% load crispy_forms_tags %}
{% block conteudo %}
<div class="d-flex justify-content-center mb-5"></div>
    <div class="card-produto">
        <div class="card-header">
            <h3>G & G COTAÇÕES</h3>
            <h4>Produto</h4>
        </div>
        <div class="card-body">
            <form id="formExemplo" data-toggle="validator" role="form" action="." method="get">
              {% csrf_token %}
              <div class="form-group">
                  {{ form.nome|as_crispy_field }}
              </div>
              <div class="form-group">
                  <input type="radio" name="modo_busca" id="inicia" value="1" checked="checked">
                  <label for="inicia" class="control-label">Inicia com &nbsp;&nbsp;</label>
                  <input type="radio" name="modo_busca" id="contem" value="2">
                  <label for="contem" class="control-label">Contém &nbsp;&nbsp; </label>
                  <input type="radio" name="modo_busca" id="termina" value="3">
                  <label for="termina" class="control-label">Termina com</label>
              </div>    
              <div class="form-group">
                  <a href="{% url 'produto:produto_create' %}" class="btn btn-warning"><i class="far fa-file"></i> Novo</a>
                  <button type="submit" class="btn btn-warning"><i class="fas fa-search"></i> Pesquisar</button>
              </div>
              <div class="card-footer form-group">
                  {% if primeira_vez %}
                    <p>Cadastre um novo produto ou faça uma nova consulta! (Nenhum item pesquisado)</p>
                  {% else %}
                    <p>
                        Total de registros: {{ object_list|length }} registro{{ object_list|pluralize }}
                        retornado{{ object_list|pluralize }} na pesquisa.
                    </p>
                  {% endif %}
              </div>         
            </form>
        </div>
    </div>
    <div style="color:#FFC312">
        {% if object_list %}
        <table class="table table-hover table-bordered table-sm table-responsive-sm">
          <thead class="text-center">
            <tr>
              <th colspan="4">Produto{{ object_list|pluralize:'s' }}</th>
            </tr>
            <tr>
              <th>Nome</th>
              <th>Descrição</th>
              <th>Preço</th>
              <th>Ação</th>
            </tr>
          </thead>
          <tbody>
            {% for produto in object_list %}
            <tr>
              <td width="280">{{ produto.nome }}</td>
              <td width="380">{{ produto.descricao }}</td>
              <td width="80" align="right">{{ produto.preco }}</td>
              <td>
                <a href="{% url 'produto:produto_delete' produto.id %}" class="btn btn-danger"><i
                    class="far fa-trash-alt"></i> Excluir</a>
                <a href="{% url 'produto:produto_update' produto.id %}" class="btn btn-warning"><i
                    class="far fa-edit"></i> Alterar</a>
                <a href="{% url 'produto:produto_detail' produto.id %}" class="btn btn-success"><i
                    class="fas fa-search-plus"></i>Visualizar</a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}